
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster 
  namespace: flux-system
resources:
  - ./external-dns.yaml
  # - ./infrastructure.yaml
  # - ./application.yaml
  # - ./notifications.yaml
  # - ./secrets.yaml
  # - ./sops.yaml
# patchesStrategicMerge:
#   - ./custom/external-dns.yaml